### ISSUE TITLE
string compare issue

### ISSUE THREAD

**Issue by haifenghuang** [fadion/aria#2]
In `interpreter.go`, function `runStringInfix`:
```go
func (i *Interpreter) runStringInfix(operator string, left, right string) (DataType, error) { 
	switch operator { 
	case "+": // Concat two strings. 
		return &StringType{Value: left + right}, nil 
	case "<": 
		return i.nativeToBoolean(len(left) < len(right)), nil 
	case "<=": 
		return i.nativeToBoolean(len(left) <= len(right)), nil 
	case ">": 
		return i.nativeToBoolean(len(left) > len(right)), nil 
	case ">=": 
		return i.nativeToBoolean(len(left) >= len(right)), nil 
	case "==": 
		return i.nativeToBoolean(left == right), nil 
	case "!=": 
		return i.nativeToBoolean(left != right), nil 
	case "..": // Range between two characters. 
		return i.runRangeStringInfix(left, right) 
	default: 
		return nil, fmt.Errorf("Unsupported String operator '%s'", operator) 
	} 
} 
```

You used len(str1) and len(str2) to compare two strings, this way is not very correct. In go, we could simply use `str1<str2`, `str1>=str2`, etc. that would do the compare.

**Comment by fadion** [comment]
In Aria, I wanted string comparison to compare the length of the strings. So, `"aaa" > "b"` returns `true`, because the left-hand operator is 2 characters longer than the right.

In Go however, string comparison is much more complex. It compares every byte lexically and depending on what you need, it may or may not be what you expect. Basically, `"aaa" > "b"` returns `false`.

I want to keep it the way it is, as I find it simpler and more intuitive. Go developers have generally more specific needs, so it makes sense string comparison works the way it does. I'm closing the issue, but if you have any other arguments or suggestions, feel free to comment.
